name: Build
run-name: Build
on:
  push:
    branches:
      - master
  pull_request:

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
      - name: Run test
        run: cargo test --all-features
